services:
  ctfd:
    image: ctfd/ctfd:latest
    user: root
    environment:
      - UPLOAD_FOLDER=/var/uploads
    ports:
      - "8000:8000"
    volumes:
      - ./platform/ctfd-data/ctfd.db:/opt/CTFd/CTFd/ctfd.db
      - ./platform/ctfd-data/uploads:/var/uploads
      - ./platform/ctfd-data/uploads:/opt/CTFd/CTFd/uploads
      - ./platform/challenges.html:/opt/CTFd/CTFd/themes/core/templates/challenges.html
    networks:
      - uninvited_net
    restart: always

  juice-shop:
    image: bkimminich/juice-shop:latest
    ports:
      - "3000:3000"
    networks:
      - uninvited_net
    volumes:
      - ./platform/users.yml:/juice-shop/data/static/users.yml
      - ./platform/juice-shop-server.js:/juice-shop/build/server.js
      - ./stages/stage3_crypto/evidence_photos.zip:/juice-shop/ftp/evidence_photos.zip
      - ./stages/stage3_crypto/evidence_photos.zip:/juice-shop/frontend/dist/frontend/assets/public/evidence_photos.zip
      - ./platform/juice-shop-index.html:/juice-shop/frontend/dist/frontend/index.html
    restart: always

  exchange-portal:
    build: ./platform/exchange-portal
    ports:
      - "8086:8086"
    volumes:
      - ./platform/exchange-portal/public:/app/public
    networks:
      - uninvited_net
    restart: always

networks:
  uninvited_net:
    driver: bridge
