version: '3.8'

services:
  ctfd:
    image: ctfd/ctfd:latest
    ports:
      - "8000:8000"
    networks:
      - uninvited_net
    restart: always

  juice-shop:
    image: bkimminich/juice-shop:latest
    ports:
      - "3000:3000"
    networks:
      - uninvited_net
    volumes:
      - ./platform/users.yml:/juice-shop/data/static/users.yml
      - ./platform/juice-shop-server.js:/juice-shop/build/server.js
      - ./stages/stage3_crypto/evidence_photos.zip:/juice-shop/ftp/evidence_photos.zip
      - ./stages/stage3_crypto/evidence_photos.zip:/juice-shop/frontend/dist/frontend/assets/public/evidence_photos.zip
    restart: always

  exchange-portal:
    build: ./platform/exchange-portal
    ports:
      - "8086:8086"
    networks:
      - uninvited_net
    restart: always

networks:
  uninvited_net:
    driver: bridge
